---
abstract: 'Insert copyright statement into source code files'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  File::pushd: 1.00
  Path::Class: 0
  Test::DZil: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-InsertCopyright
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::InsertCopyright:
    file: lib/Dist/Zilla/Plugin/InsertCopyright.pm
    version: 0.001
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  PPI::Document: 0
  perl: 5.008001
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-InsertCopyright
  homepage: http://github.com/dagolden/dist-zilla-plugin-insertcopyright
  repository: http://github.com/dagolden/dist-zilla-plugin-insertcopyright
version: 0.001
